/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

var fib = function(n) {
    if(n<2) {
        return 1;
    }
    return fib(n-1) + fib(n-2);
};

var evenFib = 0;
for (var i = 0; i < 35; i++) {
	if (fib(i) % 2 === 0 && fib(i) < 4000000) {
		evenFib += fib(i);
	}
};



console.log(evenFib);
/*
while (i<50) {
	var i = 0;	
	i++;	
	if (fib(i)%2===0) {
		sum+=i
	}
	return sum;
}
*/


	